import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";

// Load Montserrat font with weights from 100 to 900 and set CSS variable names
const montserratSans = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat-sans",
  weight: ["100", "900"], // Define the font weights you need
});
const montserratMono = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat-mono",
  weight: ["100", "900"], // Use appropriate weights for mono if available
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserratSans.variable} ${montserratMono.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
